Clang format (#94)
* update todo
* update line-ending settings
* set up basic formatter
* add whitespace settings
* add more configuration
* configure formatting
* add formatting check
* update docs
* record wae as complete
* find .hpp files instead of .h files
* track files
* update GHA clang-format
* filter formatted files to c++ files
* update version
* update formatter
* reduce verbosity
* update gitattributes
* renormalize codebase
* add check for line endings
* check line endings on all files
* reset line endings on .clang-format
* renormalize files
* renormalize more files
* more renormalization
* tweak GHA file
* add settings
* more styiling changes
* more styling tweaks
* format code
* adjust TODO
* fix compile error
* fix formatting
* fix docs build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -23,22 +23,83 @@ jobs:
         # macos-14:     https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
         host:
           # cl configurations
-          - { cpp_compiler: cl,         c_compiler: cl,       image: windows-2022, generator: Visual Studio 17 2022 }
-          - { cpp_compiler: cl,         c_compiler: cl,       image: windows-2025, generator: Visual Studio 17 2022 }
+          - {
+              cpp_compiler: cl,
+              c_compiler: cl,
+              image: windows-2022,
+              generator: Visual Studio 17 2022,
+            }
+          - {
+              cpp_compiler: cl,
+              c_compiler: cl,
+              image: windows-2025,
+              generator: Visual Studio 17 2022,
+            }
           # clang++ configurations
-          - { cpp_compiler: clang++-16, c_compiler: clang-16, image: ubuntu-24.04, generator: Unix Makefiles        }
-          - { cpp_compiler: clang++-17, c_compiler: clang-17, image: ubuntu-24.04, generator: Unix Makefiles        }
-          - { cpp_compiler: clang++-18, c_compiler: clang-18, image: ubuntu-24.04, generator: Unix Makefiles        }
-          - { cpp_compiler: clang++,    c_compiler: clang,    image: macos-14,     generator: Unix Makefiles        } # GHA docs say this is version 15.0.0
+          - {
+              cpp_compiler: clang++-16,
+              c_compiler: clang-16,
+              image: ubuntu-24.04,
+              generator: Unix Makefiles,
+            }
+          - {
+              cpp_compiler: clang++-17,
+              c_compiler: clang-17,
+              image: ubuntu-24.04,
+              generator: Unix Makefiles,
+            }
+          - {
+              cpp_compiler: clang++-18,
+              c_compiler: clang-18,
+              image: ubuntu-24.04,
+              generator: Unix Makefiles,
+            }
+          - {
+              cpp_compiler: clang++,
+              c_compiler: clang,
+              image: macos-14,
+              generator: Unix Makefiles,
+            } # GHA docs say this is version 15.0.0
           # g++ configurations
-          - { cpp_compiler: g++,        c_compiler: gcc,      image: windows-2022, generator: MinGW Makefiles       } # GHA docs say this is version 12.2.0
-          - { cpp_compiler: g++-12,     c_compiler: gcc-12,   image: ubuntu-24.04, generator: Unix Makefiles        }
-          - { cpp_compiler: g++-13,     c_compiler: gcc-13,   image: ubuntu-24.04, generator: Unix Makefiles        }
-          - { cpp_compiler: g++-14,     c_compiler: gcc-14,   image: ubuntu-24.04, generator: Unix Makefiles        }
-          - { cpp_compiler: g++,        c_compiler: gcc,      image: macos-14,     generator: Unix Makefiles        }
+          - {
+              cpp_compiler: g++,
+              c_compiler: gcc,
+              image: windows-2022,
+              generator: MinGW Makefiles,
+            } # GHA docs say this is version 12.2.0
+          - {
+              cpp_compiler: g++-12,
+              c_compiler: gcc-12,
+              image: ubuntu-24.04,
+              generator: Unix Makefiles,
+            }
+          - {
+              cpp_compiler: g++-13,
+              c_compiler: gcc-13,
+              image: ubuntu-24.04,
+              generator: Unix Makefiles,
+            }
+          - {
+              cpp_compiler: g++-14,
+              c_compiler: gcc-14,
+              image: ubuntu-24.04,
+              generator: Unix Makefiles,
+            }
+          - {
+              cpp_compiler: g++,
+              c_compiler: gcc,
+              image: macos-14,
+              generator: Unix Makefiles,
+            }
         include:
           - build_type: Coverage
-            host: { cpp_compiler: clang++-18, c_compiler: clang-18, image: ubuntu-24.04, generator: Unix Makefiles }
+            host:
+              {
+                cpp_compiler: clang++-18,
+                c_compiler: clang-18,
+                image: ubuntu-24.04,
+                generator: Unix Makefiles,
+              }
 
     steps:
       - name: checkout
@@ -105,6 +166,30 @@ jobs:
         with:
           files: ${{ steps.strings.outputs.tests-output-dir }}/coverage-lines.txt
           fail_ci_if_error: true
+
+  format:
+    runs-on: ubuntu-24.04
+
+    steps:
+      - name: checkout
+        uses: actions/checkout@v3
+
+      - name: Verify formatting and LF
+        run: |
+          # Fail on first file that has CRLF
+          for f in $(git ls-files); do
+              # Check LF
+              if grep -q $'\r' "$f"; then
+                  echo "File $f has CRLF line endings. Please convert to LF."
+                  exit 1
+              fi
+          done
+
+      - name: Install clang-format
+        run: sudo apt-get update && sudo apt-get install -y clang-format-20
+
+      - name: Run clang-format check
+        run: clang-format -style=file --dry-run --Werror $(git ls-files code/src/*.hpp code/tests/*.cpp code/tests/*.hpp)
 
   docs:
     runs-on: ubuntu-24.04
