add check for line endings

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -174,6 +174,17 @@ jobs:
       - name: checkout
         uses: actions/checkout@v3
 
+      - name: Verify formatting and LF
+        run: |
+          # Fail on first file that has CRLF
+          for f in $(git ls-files code); do
+              # Check LF
+              if grep -q $'\r' "$f"; then
+                  echo "File $f has CRLF line endings. Please convert to LF."
+                  exit 1
+              fi
+          done
+
       - name: Install clang-format
         run: sudo apt-get update && sudo apt-get install -y clang-format-20
 
